services:
    ta-sub-listener:
        image: thearyadev0/tubearchivist-subscription-listener:latest # or version tag
        environment:
            TUBEARCHIVIST_URL: ""
            API_TOKEN: ""
            YOUTUBE_TOKEN: ""
            AUTOSTART: "True" # or False
