services:
    ta-sub-listener:
        image: thearyadev0/tubearchivist-subscription-listener:latest # or version tag
        environment:
            TUBEARCHIVIST_URL: "" 
            API_TOKEN: "" # tubearchivist api token
            YOUTUBE_TOKEN: "" # youtube data v3 api token
            AUTOSTART: "True" # or False
            REPEAT: "50" # times to repeat in one day

            ## each channel uses 1 quota units per scan. if i have 100 channels * 1 units * 50 scans per day, it will use 5000 quota units. 
            #
            # the youtube api provides you with 10000 units per day. You may be able to request more
